### ISSUE TITLE
How to deal with generichide and elementhide?

### ISSUE THREAD

**Issue by Bangkokian** [sitexw/BlockAdBlock#10]
Sites that have generichide and elementhide filters don't get detected. Is there some way to detect these sites?

**Comment by sitexw** [comment]
Currently with the V3, this is not possible.
It will use the V4 that can also test the HTTP request and check that the advertising scripts load properly.

**Comment by harryqt** [comment]
@sitexw Users are still bypassing everything using `$generichide` it's 7 month later. any luck?

**Comment by sitexw** [comment]
I always confirms that it will never be implemented in the V3, because it requires very large changes. This is why I invite you to turn to the V4, which it supports HTTP detection that can solve this problem.
