### ISSUE TITLE
Example site fails to detect uBlock Origin

### ISSUE THREAD

**Issue by egeland** [sitexw/BlockAdBlock#13]
![image](https://cloud.githubusercontent.com/assets/1281379/21443499/40cd17b8-c8e9-11e6-9cad-37e5100bd594.png)

```
Google Chrome	55.0.2883.87 (Official Build) (64-bit)
Revision	ad0be09aa3ca814168d079b52825f6f80e22f0e8-refs/branch-heads/2883@{#723}
OS	        Linux 
JavaScript	V8 5.5.372.32
```

**Comment by sitexw** [comment]
Use the "[integrity](https://developer.mozilla.org/fr/docs/Web/Security/Subresource_Integrity)" attribute on your script's import or wait for the [BlockAdBlock V4](https://github.com/sitexw/FuckAdBlock/tree/v4.x).
