### ISSUE TITLE
Fails to detect changes in ad blocker's status. 

### ISSUE THREAD

**Issue by ghost** [sitexw/BlockAdBlock#15]
If I visit the [online example page](https://fuckadblock.sitexw.fr/blockadblock/), the page correctly displays the status of my ad blocker. 

However if I pause the ad blocker and click the example page's "check again" button, the previous status is repeated. 

Software versions:
[AdBlock for Mac Chrome version 3.8.4](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom)
Chrome for Mac version Version 55.0.2883.95
Mac OS X "El Capitan" (10.11.6)

Console logs: 
```
blockadblock.js:57 [BlockAdBlock][setOption] The option "debug" he was assigned to "true"
blockadblock.js:57 [BlockAdBlock][on] A type of event "detected" was added
blockadblock.js:57 [BlockAdBlock][on] A type of event "notDetected" was added
blockadblock.js:57 [BlockAdBlock][onload->eventCallback] A check loading is launched
blockadblock.js:57 [BlockAdBlock][_creatBait] Bait has been created
blockadblock.js:57 [BlockAdBlock][check] An audit was requested with a loop
blockadblock.js:57 [BlockAdBlock][check] A check is in progress ...
blockadblock.js:57 [BlockAdBlock][_checkBait] A check (1/5 ~1ms) was conducted and detection is positive
blockadblock.js:57 [BlockAdBlock][_stopLoop] A loop has been stopped
blockadblock.js:57 [BlockAdBlock][_destroyBait] Bait has been removed
blockadblock.js:57 [BlockAdBlock][emitEvent] An event with a positive detection was called
blockadblock.js:57 [BlockAdBlock][emitEvent] Call function 1/1
blockadblock.js:57 [BlockAdBlock][clearEvent] The event list has been cleared
// Pausing AdBlock and re-checking...
undefined
blockadblock.js:57 [BlockAdBlock][on] A type of event "detected" was added
blockadblock.js:57 [BlockAdBlock][on] A type of event "notDetected" was added
blockadblock.js:57 [BlockAdBlock][check] An audit was requested with a loop
blockadblock.js:57 [BlockAdBlock][_creatBait] Bait has been created
blockadblock.js:57 [BlockAdBlock][check] A check is in progress ...
blockadblock.js:57 [BlockAdBlock][_checkBait] A check (1/5 ~1ms) was conducted and detection is positive
blockadblock.js:57 [BlockAdBlock][_stopLoop] A loop has been stopped
blockadblock.js:57 [BlockAdBlock][_destroyBait] Bait has been removed
blockadblock.js:57 [BlockAdBlock][emitEvent] An event with a positive detection was called
blockadblock.js:57 [BlockAdBlock][emitEvent] Call function 1/1
blockadblock.js:57 [BlockAdBlock][clearEvent] The event list has been cleared
```

**Comment by sitexw** [comment]
It is normal that it will start the detection process again if you call the "check" method again.
But I'm afraid I did not understand the problem.

**Comment by ghost** [comment]
If I have AdBlock unpaused, and I visit the online example, the page correctly displays "AdBlock is enabled".  However, if I then pause AdBlock and click the "Check again" button, the page still reports "enabled", whereas I would expect it now to report "not enabled". 

Similarly, if I have AdBlock paused, and I visit the online example, the page correctly displays "AdBlock is not enabled". However, if I then unpause AdBlock and click the "Check again" button, the page still reports "not enabled", whereas I would expect it now to report "enabled".

**Comment by sitexw** [comment]
Ok, I had not understood the notion of "pause" (to disable AdBlock).

In this case, it is not the responsibility of BlockAdBlock, because disabling AdBlock (via its menu) will really disable it only after the page is reloaded.

For example, you can try to display ads after 30 seconds after the page loads and in the meantime disable AdBlock, you will see that the ads will still be blocked. Because for the deactivation to be really effective, you have to reload the page.

**Comment by ghost** [comment]
> …disabling AdBlock (via its menu) will really disable it only after the page is reloaded…

This is technically not true. As soon as AdBlock is paused, it stops blocking ad-related content. 

We have noticed that AdBlock causes failure on invocations of our in-house API call to save a form's data. This is not on a public page, and the page has no ads. Refreshing the page would not be an option, because form data would then be lost. 

Toggling AdBlock off prevents that API error, so I was hoping to be able to detect and re-detect the status of our users' ad blockers.

**Comment by ghost** [comment]
I have also tried deleted and re-instantiating the BlockAdBlock object and forcing a re-check. But it continually reports the original state, rather than the updated state. 

Is there some other way to re-check that I'm missing? Why have a re-check button at all? 

Thank you.

**Comment by sitexw** [comment]
To be exact, AdBlock is partially disabled.
That is, the detection of advertisements by the DOM (HTML) is still functional, but the interception of HTTP requests is disabled. As the V3 of BlockAdBlock works with detection by the DOM, this is why it continues to detect AdBlock.

For your particular case, it would be necessary to set up an HTTP detection. I propose 2 solutions either you realize this detection yourself by detecting the blocking of the sending of your form, or you use the [V4 of FuckAdBlock](https://github.com/sitexw/FuckAdBlock/tree/v4.x) with only the detection by HTTP.

**Comment by ghost** [comment]
I see. Thank you.

**Comment by sitexw** [comment]
To use the V4, I advise you to instantiate yourself :
https://fuckadblock.sitexw.fr/beta/#Instance_222
And to run the "check" manually with only HTTP detection:
```javascript
myFuckAdBlock.check(['http']);
```

But AdBlock can put a sticks in the wheels, blocking the FuckAdBlock script, preventing you from manual instantiation and "check".
