### ISSUE TITLE
blockadblock.js is not blocked by Adblocker

### ISSUE THREAD

**Issue by ZRktty** [sitexw/BlockAdBlock#19]
Important notice,
that `blockadblock.js` is not blocked bacause it's not in the easylist (check https://easylist-downloads.adblockplus.org/easylist.txt).
However, the script named `fuckadblock.js` script gets blocked when Adblock & ABP is present in users' browser!
Unfortunately, **fuckadblock.js** is not so convenient name in production code, but you can use a js file called `abdetect.js` instead.

**Comment by sitexw** [comment]
Indeed, this makes detection more efficient if the file is blocked, but the detection via Javascript works quite. So in the end, it should not have any impact.
In the worst case, you can rename "blockadblock.js" to "ads.js" ;)

**Comment by JohnMH** [comment]
Renaming to "ads.js" would just trigger a different filter.
