### ISSUE TITLE
uBlock Origin support

### ISSUE THREAD

**Issue by luca7766** [sitexw/BlockAdBlock#26]
Hi, is there a way to detect also uBlock Origin, are you planning to make an updated version in the near future? Thank your for your work.

**Comment by fanguitocoder** [comment]
When you have uBlock active, BlockAdBlock don't work, you can't even see the debug in the console. Any update about uBlock? Thank you so much!

**Comment by luca7766** [comment]
Hey, this website uses a modified version of the js, seems they just changed the name of the file and the function name, and it works also with ublock, take a look :-) 
https :// www. mylivesignature .com/    (remove spaces)

**Comment by sitexw** [comment]
Use the advanced detection mechanisms highlighted in the readme file, in the "Code example" section.
