### ISSUE TITLE
bower install fuck-adblock

### ISSUE THREAD

**Issue by etx** [sitexw/BlockAdBlock#3]
Bonjour! 

You've still got `bower install fuck-adblock` on your demo site. Awesome lib, look forward to using and contributing!

**Comment by sitexw** [comment]
Indeed, I had not paid attention. I do that this morning.

Merci et bonne journée.

**Comment by sitexw** [comment]
It is done (https://github.com/sitexw/BlockAdBlock/commit/fbf00b5a9f7755d2b2864fa12797a506c60213a4)
