### ISSUE TITLE
Does not detect DuckDuckGo Privacy Essentials

### ISSUE THREAD

**Issue by sethlivingston** [sitexw/BlockAdBlock#32]
![image](https://user-images.githubusercontent.com/574793/45169073-6f11a800-b1c2-11e8-870a-224defd474fc.png)

I suspect it does more sophisticated blocking than what early ad blockers did.

**Comment by PrivateGER** [comment]
Privacy Essentials does not block ads, as far as I know.

**Comment by sitexw** [comment]
Indeed, DuckDuckGo does not block advertising.
But you can very well set up a DuckDuckGo detection plugin and use it in FuckAdBlock V4.
Even ideally, to offer it to the community.
