### ISSUE TITLE
Detect ADBlock  dynamic

### ISSUE THREAD

**Issue by yuanchieh-cheng** [sitexw/BlockAdBlock#33]
The BlockAdBlock would detect correctly only when page refresh.  
I turn on and off adblock after a while, BlockAdBlock cannot detect.   

It suppose to detect the correct result whenever I call `BlockAdBlock.check()`

**Comment by sitexw** [comment]
It is easier to detect AdBlock at the launch of the page than after.
In addition, if AdBLock has blocked the FuckAdBlock script, it means that the detection is positive, but also that the script did not import. So a new detection is impossible because FuckAdBLock could never be imported.
