### ISSUE TITLE
No longer works for adblock plus

### ISSUE THREAD

**Issue by samburdge** [sitexw/BlockAdBlock#42]
Visiting your demo link (https://fuckadblock.sitexw.fr/blockadblock/) with Adblock Plus enabled, it does not detect the adblocker any more. This appears to have changed in the last couple of days.
All of my applications using blockadblock are experiencing the same problem.

**Comment by sitexw** [comment]
Hello, thanks for the info, I just fixed the sample version, which was implemented with the old system. I strongly advise you to use the example in README, or even to orient yourself towards [V4 (Beta)](https://fuckadblock.sitexw.fr/beta/).

Have a good day.

**Comment by quan17** [comment]
> Hello, thanks for the info, I just fixed the sample version, which was implemented with the old system. I strongly advise you to use the example in README, or even to orient yourself towards [V4 (Beta)](https://fuckadblock.sitexw.fr/beta/).
> 
> Have a good day.

@sitexw Sorry if I reopen this issue, but do you mind to make V4 support in this library as well, since the name f word will be a small problem when we use it in our product.
