### ISSUE TITLE
Not working on Firefox with Adblock Plus

### ISSUE THREAD

**Issue by gunnsth** [sitexw/BlockAdBlock#5]
The script claims Adblock is enabled even if it has been disabled for the specific page or even the whole domain.  Seems specific to Firefox with Adblock Plus.  Tested in Firefox 42 with Adblock Plus 2.7 on both MacOS and Windows 7.

Verified to happen on the demo page: http://fuckadblock.sitexw.fr/blockadblock/

**Comment by Daijobou** [comment]
Under Firefox 43 2.7.1 demo page is working fine. (win8.1)

**Comment by dotfo** [comment]
This is still an issue with ABP in Firefox 44.
Works on test page, but it is randomly detected in Firefox, even if a many ads have been loaded and ABP is disabled.

**Comment by efreeti** [comment]
It's also not working under Chrome since quite a while (maybe month). The variable name is not blocked (so it's not undefined) but the detection callback is never called. I think they made some update. Is there any chance this is gonna be fixed soon?

**Comment by efreeti** [comment]
The demo page does work though

**Comment by talha-asad** [comment]
Demo page says enabled, when it's paused or disabled for the domain. Tested on Chrome 51 OS X 10.11.5 (AdBlock)

**Comment by sitexw** [comment]
I invite you to turn to the [V4](https://github.com/sitexw/FuckAdBlock/tree/v4.x) of BlockAdBlock.
