### ISSUE TITLE
possible to have a toggle return ?

### ISSUE THREAD

**Issue by ghost** [sitexw/BlockAdBlock#9]
just wondering if it possible to return a simple true|false statement on test... it may be simplier to integrate with already custom js script.

example : 

```
if(typeof blockAdBlock === 'undefined') {
            adb = 0; /* 0 = false */
        } else {
            adb = blockAdBlock.toggleTestReturn(); /* return 0 or 1 */
        }
```

**Comment by joshuaharrison** [comment]
maybe you could use

`blockAdBlock.check(loop);`
